
config_suite.config_suite_form:
  path: '/admin/config/config_suite/admin_settings'
  defaults:
    _form: '\Drupal\config_suite\Form\AdminSettingsForm'
    _title: 'AdminSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

