config_suite.settings:
  type: config_object
  label: 'Config Suite settings'
  mapping:
    automatic_import:
      type: boolean
      label: 'automatic import'
    automatic_export:
      type: boolean
      label: 'automatic export'